@startuml  App Installation & User Registration

title
Usecase 1-3
User Registration / App Installation
end title

autonumber

actor Civ as "Civilian\nUser"
actor Off as "Officer\nUser"

box "Hey Blue" #Lightblue
    participant Desktop as "Desktop\nWebside"
    participant Mobile as "Mobile\nApp"

    participant API_Layer as "Hey Blue\nAPI Layer"

    participant ID_DB as "Hey Blue\nIdentity Database"
    participant GOV_DB as "Hey Blue\nGoverment Database"
end box

box "External Services" 
    participant Appstore as "App Stores"
    participant FIS as "Federated Identity Services"
end box

'##### App Installation

opt App installation workflow
Civ --> Civ : Opens Device App Store
Off --> Off : Opens Device App store
 activate Civ
 activate Off
    activate Appstore
    Civ -> Appstore : search App and request for installation
    Appstore -> Civ : install app
    Off -> Appstore : search App and request for installation
    Appstore -> Civ : install app
    deactivate Appstore 
end


'###### User Registration

opt User Registration


end




'###### missing
' Fill the gov DB or manual check via Admin GUI

@enduml 